### PR TITLE
Add extra acl, gce and ec2 config variables

### LINKED ISSUE #192: retry_join_ec2 configuration settings missing
Hello,

Would it be possible to add the following configuration options to this role:

https://www.consul.io/docs/agent/options.html#retry_join_ec2

That way we can join a cluster more dynamically, based on ec2 tags.

### PR DESCRIPTION
**Pull request by aairey**
Changes:
* Add `retry_join_ec2` variables (Fixes #192)
* Add `retry_join_gce` variables
* Add `acl_enforce_version_8` variable
* update README to show existing `acl` capabilities

### CODE REVIEW

**Comment by aairey** [comment]
ping @savagegus ? :)

**Comment by wanderanimrod** [comment]
Is @savagegus still there? There's a number of issues like this one that are pending merges or were merged but never released. #184, #183. 

Does anyone else but @savagegus have admin rights to this repo?

**Comment by DanishKhakwani** [comment]
@savagegus Hi! Can this be merged soon?

**Comment by DanishKhakwani** [comment]
@aairey Can you make sure that **start_join** is not defined when **ec2** or **gc2** options are used?

**Comment by DanishKhakwani** [comment]
@aairey sorry my bad, i can make **consul_join_at_start: false** or don't define it at all :)

**Comment by aairey** [comment]
@mattfinlayson is this still relevant?

**Comment by wanderanimrod** [comment]
I haven't used this in many years, so I don't know.

**Comment by mattfinlayson** [comment]
Same

**Pull request closed without merging**
